[package]
name = "chutes-ladders-analysis"
version = "0.1.0"
authors = ["johnellmore"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
csv = "~1.1"
serde = { version = "~1.0", features = ["derive"] }
